### ISSUE TITLE
Problem with "print"

### ISSUE THREAD

**Issue by Govi59** [bdesham/py-chrome-bookmarks#7]
Hi,
I am very interested in your scripts and I tried to execute py-chrome-bookmarks.py
Here is the problem :

![capture](https://cloud.githubusercontent.com/assets/22171202/22104426/5b52583a-de3f-11e6-8c0b-e5ca38eae31c.PNG)

I am not good in Python at all, sorry if I misunderstand the problem.
I run the script in cmd.exe on Windows 10 1607.

Thank you :)

**Comment by bdesham** [comment]
The script was written to work with Python 2 but you’re using Python 3, hence the error. I should be able to update the script sometime in the next couple of days.

**Comment by Govi59** [comment]
Thank you for your answer ! I'm installing Python 2.7.13.

**Comment by bdesham** [comment]
This is fixed: the scripts now support Python 2.7 and Python 3.2–3.6.
